spring:
  application:
    name: CryptoWebMessenger
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_messenger
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true